[package]
name = "ec-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anstream = "0.6.21"
anstyle = "1.0.13"
chrono = "0.4.44"
hex = "0.4.3"
hickory-proto = { version = "0.25.2", default-features = false, features = ["std"] }
legacy-tls = { version = "0.1.0", path = "../legacy-tls" }
quick-xml = "0.39.2"
reqwest = { version = "0.13.2", default-features = false, features = ["blocking", "rustls-no-provider"] }
rsa = "0.9.10"
rustls = { version = "0.23.45", default-features = false, features = ["std", "tls12"] }
rustls-rustcrypto = "0.0.2-alpha"
socket2 = { version = "0.6.2", features = ["all"] }
smoltcp = { version = "0.12.0", default-features = false, features = ["std", "proto-ipv4", "socket", "socket-tcp", "medium-ip", "alloc"] }
thiserror = "2.0.18"
urlencoding = "2.1.3"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_System_IO"] }
